[project]
name = "taller-practico-2-g1"
version = "0.1.0"
description = "Sistema RAG para EcoMarket usando LangChain y ChromaDB"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chromadb>=0.4.24",
    "fastembed>=0.2.0",
    "langchain>=0.1.0",
    "langchain-community>=0.0.20",
    "langchain-core>=0.1.20",
    "langchain-text-splitters>=0.0.1",
    "matplotlib>=3.8.0",
]
